# Generated by Django 2.0.1 on 2020-03-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200320_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
